// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqDr0UgTamuxNH4QO1YRAkiM-sHSQDP8Y',
    appId: '1:230952579989:web:f6c10b462597598cb07c9c',
    messagingSenderId: '230952579989',
    projectId: 'audio-book-9ea77',
    authDomain: 'audio-book-9ea77.firebaseapp.com',
    storageBucket: 'audio-book-9ea77.appspot.com',
    measurementId: 'G-RX9FLCEEMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUZThDVr-bg97y_zIXU9wYkp35G3OfD8',
    appId: '1:230952579989:android:4eb97cef94b9de59b07c9c',
    messagingSenderId: '230952579989',
    projectId: 'audio-book-9ea77',
    storageBucket: 'audio-book-9ea77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_GsvmIf_eXt159sfqeIhoVwsyGdEKXc',
    appId: '1:230952579989:ios:380a30582b2499e1b07c9c',
    messagingSenderId: '230952579989',
    projectId: 'audio-book-9ea77',
    storageBucket: 'audio-book-9ea77.appspot.com',
    iosBundleId: 'com.example.audioBook',
  );
}
